import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { LayoutComponent } from './layout/layout.component';
import { ConfidenceModuleComponent } from './pages/confidence-module/confidence-module.component';
import { ConfidenceWeek1L1Component } from './pages/confidence-module/confidence-week1/confidence-week1-l1/confidence-week1-l1.component';
import { ConfidenceWeek1L2Component } from './pages/confidence-module/confidence-week1/confidence-week1-l2/confidence-week1-l2.component';
import { ConfidenceWeek1L3Component } from './pages/confidence-module/confidence-week1/confidence-week1-l3/confidence-week1-l3.component';
import { ConfidenceWeek1Component } from './pages/confidence-module/confidence-week1/confidence-week1.component';
import { ConfidenceWeek2L1Component } from './pages/confidence-module/confidence-week2/confidence-week2-l1/confidence-week2-l1.component';
import { ConfidenceWeek2L2Component } from './pages/confidence-module/confidence-week2/confidence-week2-l2/confidence-week2-l2.component';
import { ConfidenceWeek2L3Component } from './pages/confidence-module/confidence-week2/confidence-week2-l3/confidence-week2-l3.component';
import { ConfidenceWeek2Component } from './pages/confidence-module/confidence-week2/confidence-week2.component';
import { ConfidenceWeek3L1Component } from './pages/confidence-module/confidence-week3/confidence-week3-l1/confidence-week3-l1.component';
import { ConfidenceWeek3L2Component } from './pages/confidence-module/confidence-week3/confidence-week3-l2/confidence-week3-l2.component';
import { ConfidenceWeek3L3Component } from './pages/confidence-module/confidence-week3/confidence-week3-l3/confidence-week3-l3.component';
import { ConfidenceWeek3Component } from './pages/confidence-module/confidence-week3/confidence-week3.component';
import { ConfidenceWeek4L1Component } from './pages/confidence-module/confidence-week4/confidence-week4-l1/confidence-week4-l1.component';
import { ConfidenceWeek4L2Component } from './pages/confidence-module/confidence-week4/confidence-week4-l2/confidence-week4-l2.component';
import { ConfidenceWeek4L3Component } from './pages/confidence-module/confidence-week4/confidence-week4-l3/confidence-week4-l3.component';
import { ConfidenceWeek4L4Component } from './pages/confidence-module/confidence-week4/confidence-week4-l4/confidence-week4-l4.component';
import { ConfidenceWeek4Component } from './pages/confidence-module/confidence-week4/confidence-week4.component';
import { DashboardComponent } from './pages/dashboard/dashboard.component';
import { EmpathyModuleComponent } from './pages/empathy-module/empathy-module.component';
import { EmpathyWeek1Component } from './pages/empathy-module/empathy-week1/empathy-week1.component';
import { EmpathyWk1L1Component } from './pages/empathy-module/empathy-week1/empathy-wk1-l1/empathy-wk1-l1.component';
import { EmpathyWk1L2Component } from './pages/empathy-module/empathy-week1/empathy-wk1-l2/empathy-wk1-l2.component';
import { EmpathyWeek2Component } from './pages/empathy-module/empathy-week2/empathy-week2.component';
import { EmpathyWk2L1Component } from './pages/empathy-module/empathy-week2/empathy-wk2-l1/empathy-wk2-l1.component';
import { EmpathyWk2L2Component } from './pages/empathy-module/empathy-week2/empathy-wk2-l2/empathy-wk2-l2.component';
import { EmpathyWk2L3Component } from './pages/empathy-module/empathy-week2/empathy-wk2-l3/empathy-wk2-l3.component';
import { EmpathyWeek3Component } from './pages/empathy-module/empathy-week3/empathy-week3.component';
import { EmpathyWk3L1Component } from './pages/empathy-module/empathy-week3/empathy-wk3-l1/empathy-wk3-l1.component';
import { EmpathyWk3L2Component } from './pages/empathy-module/empathy-week3/empathy-wk3-l2/empathy-wk3-l2.component';
import { EmpathyWk3L3Component } from './pages/empathy-module/empathy-week3/empathy-wk3-l3/empathy-wk3-l3.component';
import { EmpathyWeek4Component } from './pages/empathy-module/empathy-week4/empathy-week4.component';
import { EmpathyWk4L1Component } from './pages/empathy-module/empathy-week4/empathy-wk4-l1/empathy-wk4-l1.component';
import { EmpathyWk4L2Component } from './pages/empathy-module/empathy-week4/empathy-wk4-l2/empathy-wk4-l2.component';
import { EmpathyWk4L3Component } from './pages/empathy-module/empathy-week4/empathy-wk4-l3/empathy-wk4-l3.component';
import { FifthWeekLevel1Component } from './pages/fifth-week-welcome/fifth-week-level1/fifth-week-level1.component';
import { FifthWeekLevel2Component } from './pages/fifth-week-welcome/fifth-week-level2/fifth-week-level2.component';
import { FifthWeekLevel3Component } from './pages/fifth-week-welcome/fifth-week-level3/fifth-week-level3.component';
import { FifthWeekLevel4Component } from './pages/fifth-week-welcome/fifth-week-level4/fifth-week-level4.component';
import { FifthWeekLevel5Component } from './pages/fifth-week-welcome/fifth-week-level5/fifth-week-level5.component';
import { FifthWeekLevel6Component } from './pages/fifth-week-welcome/fifth-week-level6/fifth-week-level6.component';
import { FifthWeekLevel7Component } from './pages/fifth-week-welcome/fifth-week-level7/fifth-week-level7.component';
import { FifthWeekWelcomeComponent } from './pages/fifth-week-welcome/fifth-week-welcome.component';
import { FirstWeekLevel1Component } from './pages/first-week-welcome/first-week-level1/first-week-level1.component';
import { FirstWeekLevel2Component } from './pages/first-week-welcome/first-week-level2/first-week-level2.component';
import { FirstWeekLevel3Component } from './pages/first-week-welcome/first-week-level3/first-week-level3.component';
import { FirstWeekLevel4Component } from './pages/first-week-welcome/first-week-level4/first-week-level4.component';
import { FirstWeekLevel5Component } from './pages/first-week-welcome/first-week-level5/first-week-level5.component';
import { FirstWeekLevel6Component } from './pages/first-week-welcome/first-week-level6/first-week-level6.component';
import { FirstWeekWelcomeComponent } from './pages/first-week-welcome/first-week-welcome.component';
import { FourthWeekLevel1Component } from './pages/fourth-week-welcome/fourth-week-level1/fourth-week-level1.component';
import { FourthWeekLevel2Component } from './pages/fourth-week-welcome/fourth-week-level2/fourth-week-level2.component';
import { FourthWeekLevel3Component } from './pages/fourth-week-welcome/fourth-week-level3/fourth-week-level3.component';
import { FourthWeekLevel4Component } from './pages/fourth-week-welcome/fourth-week-level4/fourth-week-level4.component';
import { FourthWeekLevel6Component } from './pages/fourth-week-welcome/fourth-week-level6/fourth-week-level6.component';
import { FourthWeekLevel7Component } from './pages/fourth-week-welcome/fourth-week-level7/fourth-week-level7.component';
import { FourthWeekWelcomeComponent } from './pages/fourth-week-welcome/fourth-week-welcome.component';
import { GamesPageComponent } from './pages/games-page/games-page.component';
import { HomeComponent } from './pages/home/home.component';
import { IdentityModuleComponent } from './pages/identity-module/identity-module.component';
import { IntegrityModuleComponent } from './pages/integrity-module/integrity-module.component';
import { LoginComponent } from './pages/login/login.component';
import { ModuleProjectComponent } from './pages/module-project/module-project.component';
import { PlanningModuleComponent } from './pages/planning-module/planning-module.component';
import { PlanningWeek1L1Component } from './pages/planning-module/planning-week1/planning-week1-l1/planning-week1-l1.component';
import { PlanningWeek1L2Component } from './pages/planning-module/planning-week1/planning-week1-l2/planning-week1-l2.component';
import { PlanningWeek1L3Component } from './pages/planning-module/planning-week1/planning-week1-l3/planning-week1-l3.component';
import { PlanningWeek1Component } from './pages/planning-module/planning-week1/planning-week1.component';
import { PlanningWeek2Level1Component } from './pages/planning-module/planning-week2/planning-week2-level1/planning-week2-level1.component';
import { PlanningWeek2Level2Component } from './pages/planning-module/planning-week2/planning-week2-level2/planning-week2-level2.component';
import { PlanningWeek2Level3Component } from './pages/planning-module/planning-week2/planning-week2-level3/planning-week2-level3.component';
import { PlanningWeek2Component } from './pages/planning-module/planning-week2/planning-week2.component';
import { PlanningWeek3L1Component } from './pages/planning-module/planning-week3/planning-week3-l1/planning-week3-l1.component';
import { PlanningWeek3L2Component } from './pages/planning-module/planning-week3/planning-week3-l2/planning-week3-l2.component';
import { PlanningWeek3L3Component } from './pages/planning-module/planning-week3/planning-week3-l3/planning-week3-l3.component';
import { PlanningWeek3Component } from './pages/planning-module/planning-week3/planning-week3.component';
import { PlanningWeek4L1Component } from './pages/planning-module/planning-week4/planning-week4-l1/planning-week4-l1.component';
import { PlanningWeek4L2Component } from './pages/planning-module/planning-week4/planning-week4-l2/planning-week4-l2.component';
import { PlanningWeek4L3Component } from './pages/planning-module/planning-week4/planning-week4-l3/planning-week4-l3.component';
import { PlanningWeek4Component } from './pages/planning-module/planning-week4/planning-week4.component';
import { RespectModuleComponent } from './pages/respect-module/respect-module.component';
import { RespectWeek1Component } from './pages/respect-module/respect-week1/respect-week1.component';
import { RespectWk1L1Component } from './pages/respect-module/respect-week1/respect-wk1-l1/respect-wk1-l1.component';
import { RespectWk1L2Component } from './pages/respect-module/respect-week1/respect-wk1-l2/respect-wk1-l2.component';
import { RespectWeek2Component } from './pages/respect-module/respect-week2/respect-week2.component';
import { RespectWk2L1Component } from './pages/respect-module/respect-week2/respect-wk2-l1/respect-wk2-l1.component';
import { RespectWk2L2Component } from './pages/respect-module/respect-week2/respect-wk2-l2/respect-wk2-l2.component';
import { RespectWeek3Component } from './pages/respect-module/respect-week3/respect-week3.component';
import { RespectWk3L1Component } from './pages/respect-module/respect-week3/respect-wk3-l1/respect-wk3-l1.component';
import { RespectWk3L2Component } from './pages/respect-module/respect-week3/respect-wk3-l2/respect-wk3-l2.component';
import { RespectWeek4Component } from './pages/respect-module/respect-week4/respect-week4.component';
import { RespectWk4L1Component } from './pages/respect-module/respect-week4/respect-wk4-l1/respect-wk4-l1.component';
import { RespectWk4L2Component } from './pages/respect-module/respect-week4/respect-wk4-l2/respect-wk4-l2.component';
import { SecondWeekLevel1Component } from './pages/second-week-welcome/second-week-level1/second-week-level1.component';
import { SecondWeekLevel2Component } from './pages/second-week-welcome/second-week-level2/second-week-level2.component';
import { SecondWeekLevel3Component } from './pages/second-week-welcome/second-week-level3/second-week-level3.component';
import { SecondWeekLevel4Component } from './pages/second-week-welcome/second-week-level4/second-week-level4.component';
import { SecondWeekLevel5Component } from './pages/second-week-welcome/second-week-level5/second-week-level5.component';
import { SecondWeekLevel6Component } from './pages/second-week-welcome/second-week-level6/second-week-level6.component';
import { SecondWeekLevel7Component } from './pages/second-week-welcome/second-week-level7/second-week-level7.component';
import { SecondWeekWelcomeComponent } from './pages/second-week-welcome/second-week-welcome.component';
import { ThirdWeekLevel1Component } from './pages/third-week-welcome/third-week-level1/third-week-level1.component';
import { ThirdWeekLevel2Component } from './pages/third-week-welcome/third-week-level2/third-week-level2.component';
import { ThirdWeekLevel3Component } from './pages/third-week-welcome/third-week-level3/third-week-level3.component';
import { ThirdWeekLevel4Component } from './pages/third-week-welcome/third-week-level4/third-week-level4.component';
import { ThirdWeekLevel5Component } from './pages/third-week-welcome/third-week-level5/third-week-level5.component';
import { ThirdWeekLevel6Component } from './pages/third-week-welcome/third-week-level6/third-week-level6.component';
import { ThirdWeekLevel7Component } from './pages/third-week-welcome/third-week-level7/third-week-level7.component';
import { ThirdWeekWelcomeComponent } from './pages/third-week-welcome/third-week-welcome.component';

const routes: Routes = [
  { path: '', redirectTo: '/login', pathMatch: 'full' },
  { path: 'login', component: LoginComponent },
  {
    path: '',
    component: LayoutComponent,
    children: [
      { path: 'dashboard', component: DashboardComponent },
      { path: 'games', component: GamesPageComponent },
      { path: 'home', component: HomeComponent },
      { path: 'first-week', component: FirstWeekWelcomeComponent },
      { path: 'first-week-level1', component: FirstWeekLevel1Component },
      { path: 'first-week-level2', component: FirstWeekLevel2Component },
      { path: 'first-week-level3', component: FirstWeekLevel3Component },
      { path: 'first-week-level4', component: FirstWeekLevel4Component },
      { path: 'first-week-level5', component: FirstWeekLevel5Component },
      { path: 'first-week-level6', component: FirstWeekLevel6Component },
      { path: 'second-week', component: SecondWeekWelcomeComponent },
      { path: 'second-week-level1', component: SecondWeekLevel1Component },
      { path: 'second-week-level2', component: SecondWeekLevel2Component },
      { path: 'second-week-level3', component: SecondWeekLevel3Component },
      { path: 'second-week-level4', component: SecondWeekLevel4Component },
      { path: 'second-week-level5', component: SecondWeekLevel5Component },
      { path: 'second-week-level6', component: SecondWeekLevel6Component },
      { path: 'second-week-level7', component: SecondWeekLevel7Component },
      { path: 'third-week', component: ThirdWeekWelcomeComponent },
      { path: 'third-week-level1', component: ThirdWeekLevel1Component },
      { path: 'third-week-level2', component: ThirdWeekLevel2Component },
      { path: 'third-week-level3', component: ThirdWeekLevel3Component },
      { path: 'third-week-level4', component: ThirdWeekLevel4Component },
      { path: 'third-week-level5', component: ThirdWeekLevel5Component },
      { path: 'third-week-level6', component: ThirdWeekLevel6Component },
      { path: 'third-week-level7', component: ThirdWeekLevel7Component },
      { path: 'fourth-week', component: FourthWeekWelcomeComponent },
      { path: 'fourth-week-level1', component: FourthWeekLevel1Component },
      { path: 'fourth-week-level2', component: FourthWeekLevel2Component },
      { path: 'fourth-week-level3', component: FourthWeekLevel3Component },
      { path: 'fourth-week-level4', component: FourthWeekLevel4Component },
      { path: 'fourth-week-level6', component: FourthWeekLevel6Component },
      { path: 'fourth-week-level7', component: FourthWeekLevel7Component },
      { path: 'fifth-week', component: FifthWeekWelcomeComponent },
      { path: 'fifth-week-level1', component: FifthWeekLevel1Component },
      { path: 'fifth-week-level2', component: FifthWeekLevel2Component },
      { path: 'fifth-week-level3', component: FifthWeekLevel3Component },
      { path: 'fifth-week-level4', component: FifthWeekLevel4Component },
      { path: 'fifth-week-level5', component: FifthWeekLevel5Component },
      { path: 'fifth-week-level6', component: FifthWeekLevel6Component },
      { path: 'fifth-week-level7', component: FifthWeekLevel7Component },
      { path: 'identity-module', component: IdentityModuleComponent },
      { path: 'planning-module', component: PlanningModuleComponent },
      { path: 'confidence-module', component: ConfidenceModuleComponent },
      { path: 'confidence-week1', component: ConfidenceWeek1Component },
      { path: 'confidence-week1-l1', component: ConfidenceWeek1L1Component },
      { path: 'confidence-week1-l2', component: ConfidenceWeek1L2Component },
      { path: 'confidence-week1-l3', component: ConfidenceWeek1L3Component },
      { path: 'confidence-week2', component: ConfidenceWeek2Component },
      { path: 'confidence-week2-l1', component: ConfidenceWeek2L1Component },
      { path: 'confidence-week2-l2', component: ConfidenceWeek2L2Component },
      { path: 'confidence-week2-l3', component: ConfidenceWeek2L3Component },
      { path: 'confidence-week3', component: ConfidenceWeek3Component },
      { path: 'confidence-week3-l1', component: ConfidenceWeek3L1Component },
      { path: 'confidence-week3-l2', component: ConfidenceWeek3L2Component },
      { path: 'confidence-week3-l3', component: ConfidenceWeek3L3Component },
      { path: 'confidence-week4', component: ConfidenceWeek4Component },
      { path: 'confidence-week4-l1', component: ConfidenceWeek4L1Component },
      { path: 'confidence-week4-l2', component: ConfidenceWeek4L2Component },
      { path: 'confidence-week4-l3', component: ConfidenceWeek4L3Component },
      { path: 'confidence-week4-l4', component: ConfidenceWeek4L4Component },
      { path: 'module-project', component: ModuleProjectComponent },
      { path: 'planning-week1', component: PlanningWeek1Component },
      { path: 'planning-week1-l1', component: PlanningWeek1L1Component },
      { path: 'planning-week1-l2', component: PlanningWeek1L2Component },
      { path: 'planning-week1-l3', component: PlanningWeek1L3Component },
      { path: 'planning-week2', component: PlanningWeek2Component },
      { path: 'planning-week2-l1', component: PlanningWeek2Level1Component },
      { path: 'planning-week2-l2', component: PlanningWeek2Level2Component },
      { path: 'planning-week2-l3', component: PlanningWeek2Level3Component },
      { path: 'planning-week3', component: PlanningWeek3Component },
      { path: 'planning-week3-l1', component: PlanningWeek3L1Component },
      { path: 'planning-week3-l2', component: PlanningWeek3L2Component },
      { path: 'planning-week3-l3', component: PlanningWeek3L3Component },
      { path: 'planning-week4', component: PlanningWeek4Component },
      { path: 'planning-week4-l1', component: PlanningWeek4L1Component },
      { path: 'planning-week4-l2', component: PlanningWeek4L2Component },
      { path: 'planning-week4-l3', component: PlanningWeek4L3Component },
      { path: 'respect-module', component:  RespectModuleComponent },
      { path: 'respect-week1', component:  RespectWeek1Component },
      { path: 'respect-week2', component:  RespectWeek2Component },
      { path: 'respect-week3', component:  RespectWeek3Component },
      { path: 'respect-week4', component:  RespectWeek4Component },
      { path: 'respect-week1-l1', component:  RespectWk1L1Component },
      { path: 'respect-week1-l2', component:  RespectWk1L2Component },
      { path: 'respect-week2-l1', component:  RespectWk2L1Component },
      { path: 'respect-week2-l2', component:  RespectWk2L2Component },
      { path: 'respect-week3-l1', component:  RespectWk3L1Component },
      { path: 'respect-week3-l2', component:  RespectWk3L2Component },
      { path: 'respect-week4-l1', component:  RespectWk4L1Component },
      { path: 'respect-week4-l2', component:  RespectWk4L2Component },
      { path: 'empathy-module', component:  EmpathyModuleComponent },
      { path: 'empathy-week1', component:  EmpathyWeek1Component },
      { path: 'empathy-week1-l1', component:  EmpathyWk1L1Component },
      { path: 'empathy-week1-l2', component:  EmpathyWk1L2Component },
      { path: 'empathy-week2', component:  EmpathyWeek2Component },
      { path: 'empathy-week2-l1', component:  EmpathyWk2L1Component },
      { path: 'empathy-week2-l2', component:  EmpathyWk2L2Component },
      { path: 'empathy-week2-l3', component:  EmpathyWk2L3Component },
      { path: 'empathy-week3', component:  EmpathyWeek3Component },
      { path: 'empathy-week3-l1', component:  EmpathyWk3L1Component },
      { path: 'empathy-week3-l2', component:  EmpathyWk3L2Component },
      { path: 'empathy-week3-l3', component:  EmpathyWk3L3Component },
      { path: 'empathy-week4', component:  EmpathyWeek4Component },
      { path: 'empathy-week4-l1', component:  EmpathyWk4L1Component },
      { path: 'empathy-week4-l2', component:  EmpathyWk4L2Component },
      { path: 'empathy-week4-l3', component:  EmpathyWk4L3Component },
      { path: 'integrity-module', component:  IntegrityModuleComponent },
      { path: 'integrity-week1', component:  EmpathyWk4L1Component },
      // { path: 'integrity-week1-l1', component:  IntegrityWeek1Component },
      // { path: 'integrity-week1-l2', component:  IntegrityWeek2Component },
      // { path: 'integrity-week1-l3', component:  IntegrityWeek3Component },
    ]
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
